{% set name = "suspect" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1683d3aabaca95e57acb9bb624a1cab8824bc8f43c9f05730cd8195a85ee127e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py2k]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base
    - lmfit
    - parse
    - parsley
    - nibabel
    - asteval
    - pydicom
    - pywavelets
    - six
    - uncertainties

test:
  imports:
    - suspect
    - suspect.io
    - suspect.base
    - suspect.fitting
    - suspect.image
    - suspect.processing
    - suspect.scripts
    - suspect.viz

about:
  home: https://github.com/openmrslab/suspect
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: MRS processing tools
  description: |
    Suspect is a Python package for processing MR spectroscopy data. 
    It supports reading data from most common formats (with more on the 
    way) and many different algorithms for core processing steps.
    Suspect allows researchers to build custom data processing scripts 
    from reliable, modular building blocks and easily share their
    techniques with other labs around the world.
  doc_url: http://suspect.readthedocs.io/en/latest/
  dev_url: https://github.com/openmrslab/suspect

extra:
  recipe-maintainers:
    - danilomendesdias
