{% set name = "suspect" %}
{% set version = "0.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/suspect-{{ version }}.tar.gz
  sha256: d4c8dcf6693cf4d23feef0f086c395e3f2e5452fe870b2e55b460892d3d1511e

build:
  number: 0
  noarch: python
  entry_points:
    - anonymize_twix = suspect.scripts.anonymize:anonymize_twix
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - lmfit
    - nibabel
    - numpy
    - parse
    - parsley
    - pydicom
    - pywavelets
    - scipy
    - matplotlib-base
    - asteval
    - uncertainties

test:
  imports:
    - suspect
    - suspect.io
    - suspect.base
    - suspect.fitting
    - suspect.image
    - suspect.processing
    - suspect.scripts
    - suspect.viz
    - suspect.basis
  commands:
    - pip check
    - anonymize_twix --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/openmrslab/suspect
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: MRS processing tools
  description: |
    Suspect is a Python package for processing MR spectroscopy data. 
    It supports reading data from most common formats (with more on the 
    way) and many different algorithms for core processing steps.
    Suspect allows researchers to build custom data processing scripts 
    from reliable, modular building blocks and easily share their
    techniques with other labs around the world.
  doc_url: http://suspect.readthedocs.io/en/latest/
  dev_url: https://github.com/openmrslab/suspect

extra:
  recipe-maintainers:
    - danilomendesdias
