appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: tlrZD38j7TK/HhduS4cVA6RsAYqSfzU+L6IupKswvgN7RuPftia35T9H6fBkSe5R6zoUXS19eyoeM7q9ewQtH2SttpcgSq4VeFVXCKyOdSeus394zZuQux1oeWW9QrYggXo/wpOSGFIuhssF35YngqyIdUNXShjndddC2aksntvgl0enbjK/wjWf1s9gsX8zyspL81/QRRNqYpVnsQIy9r7Br803HBdn0EAlv5+x85If4n9Ig4dv0y3CPK04bFV2LtDVyLVXmCKJHdiIlxulFuDn3W1AcdC38HuqbpnXSoe1S68HlhapbAkMzh/oIqHMIlunPPkrz+EtC8tBbyPwRS9CaZkPV9CJ3JFIskSEMws2Wfl9A31sIYyxvt7nzrRE8vTTW3IxylEQ6mIAuj5DXHr7KB1UamgEqdlshvyG8+ghbj+nlpZ9Puy/w87iunnaB6smh0toBukBVM7X3Q6NbWTWMcqPw7QqE5L1SziZ+yVrcLD/2GuE56nenyozlCGEPdU2b2Qe4srrGwFMQ6en5CGnGvb9vKFo4k0tuIKYLAxXTD3CkcevXZtWM/2Rv7mTUY6SYBPwIHAaLu/rXPx+I/vJJUG0Z4/DEoJaIw3wOMbuaywnCsjuPjX+VPTe+dyky7+rDsUllF0gDabe2RXlnYYh9uHcyRzErPmOwvk9/dg=}
provider:
  win: azure
conda_forge_output_validation: true
